Repository NINI-Bros/GENISISU, pull requests merged in 2024-10, with the labels that each got.

#51 🐛 fix:#50 모바일버전 결제 오류 수정
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
Labels: :bug: 버그 수정, :gem: 기능 추가

#52 :bug: fix: #17 useLocalStorage 코드 개선 및 metadataBase 추가
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/(user)/signup/page.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/page.tsx
  src/app/layout.tsx
  src/components/drive/AddBoard.tsx
  src/components/navigation/ModelLnb.tsx
  src/hook/useLocalStorage.ts
Labels: /* 주석 추가 */, :bug: 버그 수정, :ambulance: 핫픽스

#56 🐛fix: #55 게시판 간격 조정 및 관리자 권한 필요시 로그인 이동 작업
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/types/post.ts
Labels: :gem: 기능 추가, :lipstick: 스타일

#58 :sparkles: feat: #34 카카오, 네이버 로그인 기능 추가
  .env
  next.config.mjs
  src/app/(web)/(user)/login/LoginForm.tsx
  src/auth.ts
  src/data/actions/userAction.ts
  src/types/user.ts
Labels: /* 주석 추가 */, :gem: 기능 추가

#60 :ambulance: hotfix: #59 환경설정파일 제거
  .env
  .env.local
Labels: :ambulance: 핫픽스

#62 :sparkles: feat: 네이버, 카카오, 구글 로그인 기능 추가
  auth.d.ts
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/(user)/login/SnsButton.tsx
  src/auth.ts
  src/data/actions/postAction.ts
  src/data/actions/userAction.ts
  tsconfig.json
Labels: :gem: 기능 추가, :key: API 수정, :lipstick: 스타일, :open_file_folder: 파일 추가

#61 💄style: 옵션 & 결제 페이지 반응형 작업 및 피드백 반영 완료
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section2Intro.tsx
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/app/(web)/models/[model]/(section)/Section6Spec.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobilePriceLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobileTitleLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/paymentsComplete/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/components/navigation/ModelGnb.tsx
  src/components/navigation/ModelLnb.tsx
  src/types/optionLayout.ts
Labels: :bug: 버그 수정, :lipstick: 스타일

#63 :bug: hotfix: 배포를 위한 type error 해결 (deleteComment)
  src/data/actions/postAction.ts
Labels: :ambulance: 핫픽스

#65 💄style : Header, sideGnb 추가 반응형 작업 피드백 반영 완료
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobilePriceLayout.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/css/basic_mediaQuery_950.css
  src/app/css/globals.css
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
Labels: :bug: 버그 수정, :lipstick: 스타일

#68 ✨ feat: 유저의 Default 이미지 변경과 Top 버튼 기능 추가
  src/app/(web)/(user)/signup/SignupForm.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobileTitleLayout.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/(web)/models/page.tsx
  src/app/layout.tsx
  src/auth.ts
  src/components/ButtonTop.tsx
  src/components/layout/Footer.tsx
  src/data/actions/userAction.ts
Labels: :gem: 기능 추가, :lipstick: 스타일, :open_file_folder: 파일 추가

#71 ✨feat: sideGnb 기능개발 및 관련 custom hook 개발
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery_950.css
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/hook/useModalOpenBgFix.ts
  src/hook/useRefreshDefence.ts
Labels: :gem: 기능 추가

#75 🐛 fix: #70 충돌 해결 PR (하드코딩 및 디테일 개선)
  README.md
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section2Intro.tsx
  src/app/(web)/models/[model]/(section)/Section3Color.tsx
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobileTitleLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/paymentsComplete/page.tsx
  src/app/css/basic.css
  src/app/page.tsx
  src/components/ButtonOption.tsx
  src/components/ButtonReset.tsx
  src/components/Spinner.tsx
  src/components/home/Awards.tsx
  src/components/home/Events.tsx
  src/components/home/MainPagination.tsx
  src/components/home/TestDriveApplication.tsx
  src/components/home/Vehicles.tsx
  src/components/home/Video.tsx
  src/components/layout/Footer.tsx
  src/components/navigation/ModelGnb.tsx
  src/components/navigation/ModelLnb.tsx
  src/hook/useLocalStorage.ts
  src/middleware.ts
  src/types/optionLayout.ts
  src/zustand/useModel.ts
Labels: :gem: 기능 추가, :open_file_folder: 파일 추가, :recycle: 리팩토링, :ambulance: 핫픽스

#76 🚑 hotfix: #70 충돌 해결한 PR의 코멘트 반영
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/MobileTitleLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
Labels: :ambulance: 핫픽스

#77 Feature/#34 로그인 기능 개발 브랜치 충돌 해결
  README.md
Labels: :bricks: 충돌 해결

#73 ✨feat: Header 개선 작업 완료
  src/app/css/basic.css
  src/app/css/basic_mediaQuery_950.css
  src/app/layout.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sitemap.tsx
  src/components/mainGnb/GnbMobile.tsx
  src/components/mainGnb/GnbSignSet.tsx
  src/components/mainGnb/GnbWeb.tsx
  src/zustand/useGnbWrap.ts
Labels: :gem: 기능 추가, :lipstick: 스타일
