Repository NINI-Bros/GENISISU, pull requests merged in 2024-11, with the labels that each got.

#82 💄style: 로그인/회원가입 UI 수정 및 ModelCard 초기 마운트 수정
  package.json
  public/images/g90-black-45deg.png
  public/images/genisisu_logo_b_sm.png
  public/images/gv70_croped.png
  public/images/login-bg.webp
  public/images/sns_icon/Github.png
  public/images/sns_icon/Kakaotalk.png
  public/images/sns_icon/genesis.png
  public/images/sns_icon/google.png
  public/images/sns_icon/hyundai.png
  public/images/sns_icon/naver.png
  src/app/(web)/(user)/accept/JoinLoginForm.tsx
  src/app/(web)/(user)/accept/JoinSignupForm.tsx
  src/app/(web)/(user)/accept/JoinSnsButton.tsx
  src/app/(web)/(user)/accept/SignWrapSet.tsx
  src/app/(web)/(user)/accept/page.tsx
  src/app/(web)/(user)/accept/snsIconJson.ts
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/models/ViewModelResult.tsx
  src/app/css/basic.css
  src/components/mainGnb/GnbSignSet.tsx
  src/types/product.ts
  tailwind.config.ts
  tsconfig.json
Labels: :gem: 기능 추가, :lipstick: 스타일

#83 :bulb: fix: 배포용 설정 변경
  src/app/layout.tsx
  src/data/actions/userAction.ts
  src/data/fetch/productFetch.ts
Labels: :key: API 수정

#84 🚑 fix: useSearchParams를 사용한 컴포넌트에서 발생한 배포 에러 해결
  .vscode/settings.json
  src/app/(web)/(user)/accept/JoinLoginForm.tsx
  src/app/(web)/(user)/accept/SignWrapSet.tsx
  src/app/(web)/(user)/accept/page.tsx
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/(user)/login/SnsButton.tsx
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/paymentsComplete/page.tsx
  src/app/layout.tsx
  src/components/Pagination2.tsx
  src/components/Spinner.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sitemap.tsx
  src/components/mainGnb/GnbSignSet.tsx
  src/data/actions/userAction.ts
  src/data/fetch/productFetch.ts
Labels: :ambulance: 핫픽스

#85 :bulb: fix: GNB의 제니시수 주석 처리
  src/zustand/useGnbWrap.ts
Labels: /* 주석 추가 */

#86 ♻️refactor: 메인페이지 코드 개선
  public/images/ev3_bg.png
  public/images/ev4_bg.png
  public/images/ev4_bg_02.jpg
  public/images/ev4_bg_02.png
  public/images/ev4_bg_03.jpg
  public/images/ev4_bg_04.jpg
  public/images/ev5_bg.jpg
  public/images/ev5_bg.png
  src/app/(web)/[boards]/FoldingText.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/page.tsx
  src/components/home/Awards.tsx
  src/components/home/Events.tsx
  src/components/home/Video.tsx
  src/data/fetch/productFetch.ts
  src/types/post.ts
Labels: :gem: 기능 추가, :lipstick: 스타일, :recycle: 리팩토링

#89 🐛 fix: 결제페이지 금액 오류 수정
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/(web)/models/[model]/payments/taxOptions.ts
  src/components/navigation/ModelLnb.tsx
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
  src/types/payments.ts
  src/types/post.ts
Labels: :bug: 버그 수정, :open_file_folder: 파일 추가, :recycle: 리팩토링

#90 ♻️refactor : 추가 퍼블리싱 작업 및 게시판 서버컴포넌트 변경
  src/app/(web)/[boards]/BoardView.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/TableCellData.ts
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ViewModelResult.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/css/basic_mediaQuery_950.css
  src/app/layout.tsx
  src/components/ButtonTop.tsx
  src/components/PostPagination.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/skeleton/table/skeleton_list.tsx
  src/data/fetch/postFetch.ts
  src/types/post.ts
  src/zustand/useGlobalPostSet.ts
Labels: :lipstick: 스타일, :recycle: 리팩토링
