Repository NINI-Bros/GENISISU, pull requests merged in 2024-09, with the labels that each got.

#9 ✨feat: #7 전시시승게시판 상세보기 권한설정 및 전역 로그인상태 설정
  src/app/(web)/[boards]/ListItem.tsx
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: :gem: 기능 추가, :recycle: 리팩토링

#12 🚑hotfix: #3 예상 금액 오류 해결
  .github/ISSUE_TEMPLATE/기본-템플릿.md
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/components/navigation/ModelLnb.tsx
Labels: :bug: 버그 수정

#11 ✨feat: #10 결제페이지 선택옵션값 표기 개발
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
Labels: :gem: 기능 추가

#16 ✨ feat: LNB를 통한 선택 옵션 유지 기능 추가
  env.d.ts
  genisisu/상품/상품 검색.bru
  genisisu/전시시승/게시물 조회 (keyword).bru
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/OptionReadyLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/page.tsx
  src/components/Button.tsx
  src/components/navigation/ModelLnb.tsx
  src/data/fetch/productFetch.ts
  src/hook/useLocalStorage.ts
  src/types/product.ts
  src/zustand/useModel.ts
  src/zustand/usePostItem.js
  src/zustand/useSelectStore.ts
  tailwind.config.ts
Labels: /* 주석 추가 */, :bug: 버그 수정, :gem: 기능 추가

#19 💄style: 브레이킹포인트(1366px) 이전 반응형 작업
  public/images/scrollIcon.png
  public/images/scrollIcon_g.png
  src/app/(web)/loadingTest/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section2Intro.tsx
  src/app/(web)/models/[model]/(section)/Section6Spec.tsx
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/css/globals.css
  src/components/Spinner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sitemap.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event4.tsx
  src/types/payments.ts
Labels: :lipstick: 스타일, :recycle: 리팩토링

#20 ✨feat: 전체 body layout 퍼블리싱 수정
  src/app/css/basic.css
  src/app/layout.tsx
Labels: :lipstick: 스타일, :recycle: 리팩토링

#21 🚑hotfix: 옵션페이지 퍼블리싱 수정
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/components/navigation/ModelGnb.tsx
Labels: :lipstick: 스타일, :recycle: 리팩토링

#25 ✨ feat: 로그인 및 게시글 작성 기능 개선
  README.md
  genisisu/environments/genisisu_env.bru
  genisisu/전시시승/게시물 등록.bru
  genisisu/전시시승/게시물 조회 (type).bru
  genisisu/회원/관리자 로그인.bru
  genisisu/회원/사용자 로그인.bru
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/auth.ts
  src/components/Button.tsx
  src/components/InputError.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/layout/Header.tsx
  src/data/actions/authAction.ts
  src/data/actions/postAction.ts
  src/data/actions/userAction.ts
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
  src/middleware.ts
  src/types/post.ts
  src/types/user.ts
Labels: /* 주석 추가 */, :gem: 기능 추가, :lipstick: 스타일

#24 🚑 hotfix: 반응형 작업 점검 및 수정작업
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Sitemap.tsx
Labels: :bug: 버그 수정, :lipstick: 스타일

#27 :ambulance: hotfix: #26 모델 상세에 ScrollToTop.ts 적용
  .github/ISSUE_TEMPLATE/기본-템플릿.md
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/page.tsx
  src/components/ScrollToTop.ts
Labels: :ambulance: 핫픽스

#30 ♻️ refactor: #29 결제페이지 데이터호출 코드 수정 및 정리
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/types/payments.ts
Labels: :bug: 버그 수정, :recycle: 리팩토링

#32 🚨 hotfix: #14 메인페이지 z-index값 수정
  src/app/css/basic.css
Labels: :ambulance: 핫픽스

#31 ♻️ refactor: #28 메인에서 게시글 작성 기능 개선
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/css/basic.css
  src/app/error.tsx
  src/app/page.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/mainPageComponents/Event5.tsx
  src/zustand/useModel.ts
Labels: :recycle: 리팩토링

#33 ✨ feat: #28 게시글 및 댓글 기능 추가
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/loadingTest/page.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/data/actions/postAction.ts
  src/data/fetch/postFetch.ts
  src/types/post.ts
Labels: :gem: 기능 추가, :lipstick: 스타일

#35 💄style: #14 모바일 반응형페이지 1차 작업
  package-lock.json
  package.json
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/page.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event4.tsx
  src/components/mainPageComponents/Event5.tsx
  src/components/mainPageComponents/MainPagination.tsx
Labels: :lipstick: 스타일

#36 ✨ feat: 로그인 기능 개발 및 버그 픽스 (중간 병합)
  .vscode/settings.json
  env.d.ts
  next.config.mjs
  package-lock.json
  package.json
  setupProxy.ts
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/(user)/signup/SignupForm.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section2Intro.tsx
  src/app/(web)/models/[model]/(section)/Section3Color.tsx
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/app/(web)/models/[model]/(section)/Section6Spec.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/api/proxy.ts
  src/app/css/basic.css
  src/app/layout.tsx
  src/auth.ts
  src/components/PostPagination.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sitemap.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event4.tsx
  src/components/mainPageComponents/Event5.tsx
  src/components/mainPageComponents/MainPagination.tsx
  src/components/navigation/ModelLnb.tsx
  src/data/actions/postAction.ts
  src/data/actions/userAction.ts
  src/data/fetch/genesis.ts
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
  src/data/fetch/userFetch.ts
  src/hook/session.tsx
  src/middleware.ts
  src/zustand/useSelectStore.ts
  types/address.ts
  types/file.ts
  types/index.ts
  types/payments.ts
  types/post.ts
  types/product.ts
  types/response.ts
  types/user.ts
Labels: /* 주석 추가 */, :bug: 버그 수정, :gem: 기능 추가, :lipstick: 스타일

#37 💄style: #14 모바일 반응형페이지 2차 작업
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/(user)/signup/page.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/page.tsx
  src/app/css/basic.css
  src/app/css/basic_mediaQuery.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Spinner.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/mainPageComponents/Event4.tsx
  src/components/navigation/ModelGnb.tsx
  src/components/navigation/ModelLnb.tsx
Labels: :lipstick: 스타일, :recycle: 리팩토링

#45 ♻️refactor: #39 img 태그 사용 오류 수정
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/components/navigation/ModelGnb.tsx
Labels: :bug: 버그 수정, :lipstick: 스타일

#46 병합 충돌 문제 해결
  .eslintrc.json
  .gitignore
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/auth.ts
  src/components/Button.tsx
  src/components/PostPagination.tsx
  src/components/Spinner.tsx
  src/components/drive/AddBoard.tsx
  src/components/drive/Input.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainMenu.tsx
  src/components/layout/SideMenuList.tsx
  src/components/layout/Sitemap.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event4.tsx
  src/components/mainPageComponents/MainPagination.tsx
  src/components/navigation/ModelGnb.tsx
  src/components/navigation/ModelLnb.tsx
  src/data/fetch/genesis.ts
  src/hook/session.tsx
  src/types/address.ts
  src/zustand/useProfile.js
Labels: :ambulance: 핫픽스

#47 🚑 hotfix: 병합 문제 해결
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/layout.tsx
  src/components/layout/Sitemap.tsx
Labels: :ambulance: 핫픽스

#48 🚨hotfix: 결제페이지 초기 데이터호출 수정
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
Labels: :ambulance: 핫픽스
